// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:478057ca-b687-42ee-930f-2f770c39b4d1',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'amsterdamar-hosting-mobilehub-1708327480',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd34u8bu0p77v10.cloudfront.net',
    'aws_mobile_analytics_app_id': '276a54a7a0be417a92797c1d8b10f82c',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '88b5cd7a-21c5-11e8-819f-0b05622f0656',
    'aws_project_name': 'AmsterdamAR',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'amsterdamar-mobilehub-1708327480',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'amsterdamar-userfiles-mobilehub-1708327480',
    'aws_user_files_s3_bucket_region': 'us-east-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_nMrrAinKJ',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '6huade18gqji19nrep59jms042',
}

export default awsmobile;
